(component
  (canon context.get i32 0 (core func $get))
  (canon context.set i32 0 (core func $set))
  (canon task.return (core func $return))
  (core module $D
    (import "" "get" (func $get (result i32)))
    (import "" "set" (func $set (param i32)))
    (global $seen (mut i32) (i32.const -1))
    (func (export "dtor") (param i32)
      (global.set $seen (call $get))
      (call $set (i32.const 99)))
    (func (export "seen") (result i32) (global.get $seen)))
  (core instance $d (instantiate $D (with "" (instance
    (export "get" (func $get)) (export "set" (func $set))))))
  (type $R (resource (rep i32) (dtor (core func $d "dtor"))))
  (canon resource.new $R (core func $new))
  (canon resource.drop $R (core func $drop))
  (core module $M
    (import "" "new" (func $new (param i32) (result i32)))
    (import "" "drop" (func $drop (param i32)))
    (import "" "get" (func $get (result i32)))
    (import "" "set" (func $set (param i32)))
    (import "" "return" (func $return))
    (func $probe (export "probe") (result i32)
      (call $set (i32.const 42))
      (call $drop (call $new (i32.const 7)))
      (call $get))
    (func (export "async-probe") (result i32)
      (if (i32.ne (call $probe) (i32.const 42)) (then unreachable))
      (call $return)
      (i32.const 0))
    (func (export "callback") (param i32 i32 i32) (result i32) unreachable))
  (core instance $m (instantiate $M (with "" (instance
    (export "new" (func $new)) (export "drop" (func $drop))
    (export "get" (func $get)) (export "set" (func $set))
    (export "return" (func $return))))))
  (func (export "probe") (result u32) (canon lift (core func $m "probe")))
  (func (export "async-probe") async
    (canon lift (core func $m "async-probe") async (callback (core func $m "callback"))))
  (func (export "seen") (result u32) (canon lift (core func $d "seen"))))
