;; Reader abandonment legally wakes the parked writer; its callback then faults.
(component
  (type $F (future u32))
  (core module $Mem (memory (export "mem") 1))
  (core instance $mem (instantiate $Mem))
  (canon future.new $F (core func $new))
  (canon future.write $F async (memory $mem "mem") (core func $write))
  (canon task.return (result $F) (core func $return))
  (canon waitable-set.new (core func $set))
  (canon waitable.join (core func $join))
  (core module $M
    (import "" "new" (func $new (result i64)))
    (import "" "write" (func $write (param i32 i32) (result i32)))
    (import "" "return" (func $return (param i32)))
    (import "" "set" (func $set (result i32)))
    (import "" "join" (func $join (param i32 i32)))
    (func (export "idle") (result i32) (i32.wrap_i64 (call $new)))
    (func (export "run") (result i32)
      (local $ends i64) (local $tx i32) (local $ws i32)
      (local.set $ends (call $new))
      (local.set $tx (i32.wrap_i64 (i64.shr_u (local.get $ends) (i64.const 32))))
      (call $return (i32.wrap_i64 (local.get $ends)))
      (if (i32.ne (call $write (local.get $tx) (i32.const 0)) (i32.const -1))
        (then unreachable))
      (local.set $ws (call $set))
      (call $join (local.get $tx) (local.get $ws))
      (i32.or (i32.const 2) (i32.shl (local.get $ws) (i32.const 4))))
    (func (export "cb") (param i32 i32 i32) (result i32) unreachable))
  (core instance $m (instantiate $M (with "" (instance
    (export "new" (func $new))
    (export "write" (func $write))
    (export "return" (func $return))
    (export "set" (func $set))
    (export "join" (func $join))))))
  (func (export "run") async (result $F)
    (canon lift (core func $m "run") async (callback (core func $m "cb"))))
  (func (export "idle") (result $F) (canon lift (core func $m "idle"))))
