;; Readable-end abandonment, delivery, and peer faults for future<own<r>>.
(component
  (import "r" (type $R (sub resource)))
  (type $F (future (own $R)))
  (core module $Mem (memory (export "mem") 1))
  (core instance $mem (instantiate $Mem))
  (canon future.drop-readable $F (core func $drop))
  (canon future.read $F async (memory $mem "mem") (core func $read))
  (canon resource.drop $R (core func $drop-r))
  (core module $M
    (import "" "mem" (memory 1))
    (import "" "drop" (func $drop (param i32)))
    (import "" "read" (func $read (param i32 i32) (result i32)))
    (import "" "drop-r" (func $drop-r (param i32)))
    (func (export "drop") (param i32) (call $drop (local.get 0)))
    (func (export "pass") (param i32) (result i32) (local.get 0))
    (func (export "fail") (param i32) unreachable)
    (func (export "take") (param i32 i32)
      (if (call $read (local.get 0) (i32.const 0)) (then unreachable))
      (call $drop-r (i32.load (i32.const 0)))
      (call $drop (local.get 0))
      (if (local.get 1) (then unreachable))))
  (core instance $m (instantiate $M (with "" (instance
    (export "mem" (memory $mem "mem"))
    (export "drop" (func $drop))
    (export "read" (func $read))
    (export "drop-r" (func $drop-r))))))
  (func (export "drop") (param "f" $F) (canon lift (core func $m "drop")))
  (func (export "pass") (param "f" $F) (result $F) (canon lift (core func $m "pass")))
  (func (export "fail") (param "f" $F) (canon lift (core func $m "fail")))
  (func (export "take") (param "f" $F) (param "trap" bool) (canon lift (core func $m "take"))))
