;; #328/#329: call settlement must precede ownership conversion.
;; Regenerate: wasm-tools parse host-settlement.wat -o host-settlement.wasm
(component
  (import "r" (type $R (sub resource)))
  (type $Result0 (result (own $R) (error (own $R))))
  (export $Result "make-result" (type $Result0))
  (type $Stream0 (stream u8))
  (export $Stream "byte-stream" (type $Stream0))
  (type $Future0 (future u32))
  (export $Future "number-future" (type $Future0))
  (import "make" (func $make async (result $Result)))
  (import "make-sync" (func $sync (param "r" (borrow $R)) (result $Result)))
  (import "producers" (instance $producers
    (type $S (stream u8))
    (type $F (future u32))
    (type $Pair0 (record (field "stream" $S) (field "future" $F)))
    (export "pair" (type $Pair (eq $Pair0)))
    (export "sources" (func async (result $Pair)))))
  (alias export $producers "sources" (func $sources))
  (import "consume" (func $consume async (param "s" $Stream) (param "f" $Future) (result u32)))
  (core module $Mem (memory (export "mem") 1))
  (core instance $mem (instantiate $Mem))
  (canon lower (func $make) async (memory $mem "mem") (core func $make-lower))
  (canon lower (func $sync) (memory $mem "mem") (core func $sync-lower))
  (canon lower (func $sources) async (memory $mem "mem") (core func $sources-lower))
  (canon lower (func $consume) async (memory $mem "mem") (core func $consume-lower))
  (canon subtask.cancel async (core func $cancel))
  (canon subtask.drop (core func $drop))
  (canon resource.drop $R (core func $drop-r))
  (canon waitable-set.new (core func $new-set))
  (canon waitable.join (core func $join))
  (canon waitable-set.poll (memory $mem "mem") (core func $poll))
  (canon waitable-set.drop (core func $drop-set))
  (core module $M
    (import "" "mem" (memory 1))
    (import "" "make" (func $make (param i32) (result i32)))
    (import "" "sync" (func $sync (param i32 i32)))
    (import "" "sources" (func $sources (param i32) (result i32)))
    (import "" "consume" (func $consume (param i32 i32 i32) (result i32)))
    (import "" "cancel" (func $cancel (param i32) (result i32)))
    (import "" "drop" (func $drop (param i32)))
    (import "" "drop-r" (func $drop-r (param i32)))
    (import "" "new-set" (func $new-set (result i32)))
    (import "" "join" (func $join (param i32 i32)))
    (import "" "poll" (func $poll (param i32 i32) (result i32)))
    (import "" "drop-set" (func $drop-set (param i32)))
    (global $h (mut i32) (i32.const 0))
    (func $settle (param $packed i32) (param $mode i32) (result i32)
      (local $state i32)
      (global.set $h (i32.shr_u (local.get $packed) (i32.const 4)))
      (if (i32.eq (local.get $mode) (i32.const 2)) (then unreachable))
      (if (result i32) (local.get $mode)
        (then
          (local.set $state (call $cancel (global.get $h)))
          (if (i32.ne (local.get $state) (i32.const -1))
            (then (call $drop (global.get $h))))
          (local.get $state))
        (else (i32.and (local.get $packed) (i32.const 15)))))
    (func (export "start") (param i32) (result i32)
      (call $settle (call $make (i32.const 0)) (local.get 0)))
    (func (export "sources") (param i32) (result i32)
      (call $settle (call $sources (i32.const 0)) (local.get 0)))
    (func (export "consume") (param i32 i32 i32) (result i32)
      (call $settle (call $consume (local.get 0) (local.get 1) (i32.const 0)) (local.get 2)))
    (func (export "sync") (param i32) (result i32)
      (call $sync (local.get 0) (i32.const 0))
      (call $drop-r (local.get 0))
      (call $drop-r (i32.load (i32.const 4)))
      (i32.load8_u (i32.const 0)))
    (func (export "finish") (result i32) (local $set i32)
      (local.set $set (call $new-set))
      (call $join (global.get $h) (local.get $set))
      (drop (call $poll (local.get $set) (i32.const 32)))
      (call $join (global.get $h) (i32.const 0))
      (call $drop-set (local.get $set))
      (call $drop (global.get $h))
      (call $drop-r (i32.load (i32.const 4)))
      (i32.load8_u (i32.const 0)))
    (func (export "ping") (result i32) (i32.const 42))
    (func (export "trap") unreachable))
  (core instance $m (instantiate $M (with "" (instance
    (export "mem" (memory $mem "mem"))
    (export "make" (func $make-lower))
    (export "sync" (func $sync-lower))
    (export "sources" (func $sources-lower))
    (export "consume" (func $consume-lower))
    (export "cancel" (func $cancel))
    (export "drop" (func $drop))
    (export "drop-r" (func $drop-r))
    (export "new-set" (func $new-set))
    (export "join" (func $join))
    (export "poll" (func $poll))
    (export "drop-set" (func $drop-set))))))
  (func (export "start") (param "mode" u32) (result u32) (canon lift (core func $m "start")))
  (func (export "sources") (param "mode" u32) (result u32) (canon lift (core func $m "sources")))
  (func (export "consume") (param "s" $Stream) (param "f" $Future) (param "mode" u32) (result u32) (canon lift (core func $m "consume")))
  (func (export "run-sync") (param "r" (borrow $R)) (result u32) (canon lift (core func $m "sync")))
  (func (export "finish") (result u32) (canon lift (core func $m "finish")))
  (func (export "ping") (result u32) (canon lift (core func $m "ping")))
  (func (export "trap") (canon lift (core func $m "trap"))))
