(component
  (import "r" (type $R (sub resource)))
  (import "next" (func $next (result (future u32))))
  (import "finish" (func $finish (param "r" (borrow $R))))
  (canon lower (func $next) (core func $next'))
  (canon lower (func $finish) (core func $finish'))
  (canon resource.drop $R (core func $drop))
  (core module $M
    (import "" "next" (func $next (result i32)))
    (import "" "finish" (func $finish (param i32)))
    (import "" "drop" (func $drop (param i32)))
    (func (export "run") (param $r i32) (result i32)
      (local $f i32)
      (call $finish (local.get $r))
      (local.set $f (call $next))
      (call $drop (local.get $r))
      (local.get $f)))
  (core instance $m (instantiate $M (with "" (instance
    (export "next" (func $next'))
    (export "finish" (func $finish'))
    (export "drop" (func $drop))))))
  (func (export "run") (param "r" (borrow $R)) (result (future u32))
    (canon lift (core func $m "run"))))
