;; wasm-tools parse resource-overlap.wat -o resource-overlap.wasm
(component
  (import "host:api/res" (instance $api
    (export "R" (type $R (sub resource)))
    (export "value" (func (param "r" (borrow $R)) (result u32)))))
  (alias export $api "R" (type $R))
  (alias export $api "value" (func $value))
  (canon lower (func $value) (core func $value'))
  (canon resource.drop $R (core func $drop))
  (core module $D
    (func (export "drop") (param i32)))
  (core instance $d (instantiate $D))
  (type $ticket (resource (rep i32) (dtor (func $d "drop"))))
  (canon resource.new $ticket (core func $new))
  (core module $M
    (import "" "value" (func $value (param i32) (result i32)))
    (import "" "drop" (func $drop (param i32)))
    (import "" "new" (func $new (param i32) (result i32)))
    (func $peek (export "peek") (param $h i32) (result i32)
      (local $out i32)
      (drop (call $value (local.get $h)))
      (local.set $out (call $value (local.get $h)))
      (call $drop (local.get $h))
      (local.get $out))
    (func (export "accept-two") (param $a i32) (param $b i32)
      (call $drop (local.get $a))
      (call $drop (local.get $b)))
    (func (export "fail") (param $h i32)
      (call $drop (local.get $h))
      unreachable)
    (func (export "hold") (param i32) (result i32) (local.get 0))
    (func (export "held-value") (param $h i32) (result i32)
      (call $value (local.get $h)))
    (func (export "return-held") (param i32) (result i32) (local.get 0))
    (export "drop-held" (func $drop))
    (func (export "ticket") (param $h i32) (result i32)
      (local $out i32)
      (local.set $out (call $value (local.get $h)))
      (call $drop (local.get $h))
      (call $new (local.get $out))))
  (core instance $i (instantiate $M (with "" (instance
    (export "value" (func $value')) (export "drop" (func $drop))
    (export "new" (func $new))))))
  (func (export "peek") (param "r" (borrow $R)) (result u32)
    (canon lift (core func $i "peek")))
  (func (export "hold") (param "r" (own $R)) (result u32)
    (canon lift (core func $i "hold")))
  (func (export "held-value") (param "h" u32) (result u32)
    (canon lift (core func $i "held-value")))
  (func (export "return-held") (param "h" u32) (result (own $R))
    (canon lift (core func $i "return-held")))
  (func (export "accept-two") (param "a" (borrow $R)) (param "b" (borrow $R))
    (canon lift (core func $i "accept-two")))
  (func (export "fail") (param "r" (borrow $R))
    (canon lift (core func $i "fail")))
  (func (export "drop-held") (param "h" u32)
    (canon lift (core func $i "drop-held")))
  (export $Ticket "ticket" (type $ticket))
  (func (export "[constructor]ticket") (param "r" (borrow $R)) (result (own $Ticket))
    (canon lift (core func $i "ticket"))))
