;; wasm-tools parse resource-overlap.wat -o resource-overlap.wasm
(component
  (import "host:api/res" (instance $api
    (export "R" (type $R (sub resource)))
    (export "value" (func (param "r" (borrow $R)) (result u32)))))
  (alias export $api "R" (type $R))
  (alias export $api "value" (func $value))
  (canon lower (func $value) (core func $value'))
  (canon resource.drop $R (core func $drop))
  (core module $D
    (global $drops (mut i32) (i32.const 0))
    (func (export "drop") (param i32)
      (global.set $drops (i32.add (global.get $drops) (i32.const 1))))
    (func (export "drops") (result i32) (global.get $drops)))
  (core instance $d (instantiate $D))
  (type $ticket (resource (rep i32) (dtor (func $d "drop"))))
  (canon resource.new $ticket (core func $new))
  (core module $M
    (import "" "value" (func $value (param i32) (result i32)))
    (import "" "drop" (func $drop (param i32)))
    (import "" "new" (func $new (param i32) (result i32)))
    (func $peek (export "peek") (param $h i32) (result i32)
      (local $out i32)
      (drop (call $value (local.get $h)))
      (local.set $out (call $value (local.get $h)))
      (call $drop (local.get $h))
      (local.get $out))
    (func (export "peek-two") (param $a i32) (param $b i32) (result i32)
      (call $peek (local.get $a))
      (call $drop (local.get $b)))
    (func (export "hold") (param i32) (result i32) (local.get 0))
    (export "drop-held" (func $drop))
    (func (export "ticket") (param $h i32) (result i32)
      (local $out i32)
      (local.set $out (call $value (local.get $h)))
      (call $drop (local.get $h))
      (call $new (local.get $out))))
  (core instance $i (instantiate $M (with "" (instance
    (export "value" (func $value')) (export "drop" (func $drop))
    (export "new" (func $new))))))
  (func (export "peek") (param "r" (borrow $R)) (result u32)
    (canon lift (core func $i "peek")))
  (func (export "hold") (param "r" (own $R)) (result u32)
    (canon lift (core func $i "hold")))
  (func (export "peek-two") (param "a" (borrow $R)) (param "b" (borrow $R)) (result u32)
    (canon lift (core func $i "peek-two")))
  (func (export "drop-held") (param "h" u32)
    (canon lift (core func $i "drop-held")))
  (export $Ticket "ticket" (type $ticket))
  (func (export "[constructor]ticket") (param "r" (borrow $R)) (result (own $Ticket))
    (canon lift (core func $i "ticket")))
  (func (export "make-ticket") (param "r" (borrow $R)) (result (own $Ticket))
    (canon lift (core func $i "ticket")))
  (func (export "ticket-drops") (result u32)
    (canon lift (core func $d "drops"))))
