;; A same-store future whose producing call cannot reach task.return until a
;; separate export opens an explicit guest gate. This makes the deferred-handle
;; window observable without host timing assumptions.
;; Regenerate: wasm-tools parse future-gated.wat -o future-gated.wasm
(component
  (type $F (future u32))
  (core module $Mem (memory (export "mem") 1))
  (core instance $mem (instantiate $Mem))
  (canon future.new $F (core func $new))
  (canon future.read $F async (memory $mem "mem") (core func $read))
  (canon future.write $F async (memory $mem "mem") (core func $write))
  (canon waitable-set.new (core func $set))
  (canon waitable.join (core func $join))
  (canon task.return (result $F) (core func $return-future))
  (canon task.return (result u32) (memory $mem "mem") (core func $return-u32))
  (core module $M
    (import "" "mem" (memory 1))
    (import "" "new" (func $new (result i64)))
    (import "" "read" (func $read (param i32 i32) (result i32)))
    (import "" "write" (func $write (param i32 i32) (result i32)))
    (import "" "set" (func $set (result i32)))
    (import "" "join" (func $join (param i32 i32)))
    (import "" "return-future" (func $return-future (param i32)))
    (import "" "return-u32" (func $return-u32 (param i32)))
    (global $value-rx (mut i32) (i32.const 0))
    (global $value-tx (mut i32) (i32.const 0))
    (global $gate-tx (mut i32) (i32.const 0))
    (global $make-set (mut i32) (i32.const 0))
    (func (export "make") (result i32)
      (local $value i64) (local $gate i64)
      (local.set $value (call $new))
      (local.set $gate (call $new))
      (global.set $value-rx (i32.wrap_i64 (local.get $value)))
      (global.set $value-tx (i32.wrap_i64 (i64.shr_u (local.get $value) (i64.const 32))))
      (global.set $gate-tx (i32.wrap_i64 (i64.shr_u (local.get $gate) (i64.const 32))))
      (if (i32.ne (call $read (i32.wrap_i64 (local.get $gate)) (i32.const 0)) (i32.const -1))
        (then unreachable))
      (global.set $make-set (call $set))
      (call $join (i32.wrap_i64 (local.get $gate)) (global.get $make-set))
      (i32.or (i32.const 2) (i32.shl (global.get $make-set) (i32.const 4))))
    (func (export "make-cb") (param $code i32) (param i32) (param $payload i32) (result i32)
      (if (i32.ne (local.get $payload) (i32.const 0)) (then unreachable))
      (if (i32.eq (local.get $code) (i32.const 4))
        (then
          (call $return-future (global.get $value-rx))
          (i32.store (i32.const 8) (i32.const 42))
          (if (i32.ne (call $write (global.get $value-tx) (i32.const 8)) (i32.const -1))
            (then unreachable))
          (call $join (global.get $value-tx) (global.get $make-set))
          (return (i32.or (i32.const 2) (i32.shl (global.get $make-set) (i32.const 4))))))
      (i32.const 0))
    (func (export "release") (result i32)
      (i32.store (i32.const 0) (i32.const 1))
      (if (i32.ne (call $write (global.get $gate-tx) (i32.const 0)) (i32.const 0))
        (then unreachable))
      (i32.const 2))
    (func (export "double") (param $rx i32) (result i32) (local $set i32) (local $status i32)
      (local.set $status (call $read (local.get $rx) (i32.const 16)))
      (if (i32.eq (local.get $status) (i32.const 0))
        (then
          (call $return-u32 (i32.mul (i32.load (i32.const 16)) (i32.const 2)))
          (return (i32.const 0))))
      (if (i32.ne (local.get $status) (i32.const -1)) (then unreachable))
      (local.set $set (call $set))
      (call $join (local.get $rx) (local.get $set))
      (i32.or (i32.const 2) (i32.shl (local.get $set) (i32.const 4))))
    (func (export "double-cb") (param $code i32) (param i32) (param $payload i32) (result i32)
      (if (i32.ne (local.get $code) (i32.const 4)) (then unreachable))
      (if (i32.ne (local.get $payload) (i32.const 0)) (then unreachable))
      (call $return-u32 (i32.mul (i32.load (i32.const 16)) (i32.const 2)))
      (i32.const 0)))
  (core instance $m (instantiate $M (with "" (instance
    (export "mem" (memory $mem "mem"))
    (export "new" (func $new))
    (export "read" (func $read))
    (export "write" (func $write))
    (export "set" (func $set))
    (export "join" (func $join))
    (export "return-future" (func $return-future))
    (export "return-u32" (func $return-u32))))))
  (func (export "make") async (result $F)
    (canon lift (core func $m "make") async (callback (core func $m "make-cb"))))
  (func (export "release") (result u32) (canon lift (core func $m "release")))
  (func (export "double") async (param "f" $F) (result u32)
    (canon lift (core func $m "double") async (memory $mem "mem") (callback (core func $m "double-cb")))))
